# Initially generated by Claude

import json
import os
import socket
import threading

from gi.repository import Adw, Gdk, GLib, Graphene, Gsk, Gtk


class NiriManager:
    def __init__(self, parent) -> None:
        self.parent = parent
        self._stop_event = threading.Event()
        self._workspaces = {}
        self._active_workspace = 1
        self._is_overview_open = False
        threading.Thread(target=self._monitor_niri, daemon=True).start()

    def _monitor_niri(self) -> None:
        socket_path = os.environ.get("NIRI_SOCKET")
        if not socket_path:
            print("[Niri] Error: NIRI_SOCKET not found.")
            return

        try:
            with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as s:
                s.connect(socket_path)
                s.sendall(b'"EventStream"\n')

                buf = ""
                ack_received = False

                while not self._stop_event.is_set():
                    chunk = s.recv(4096)
                    if not chunk:
                        print("[Niri] Socket closed by server.")
                        break

                    buf += chunk.decode("utf-8")

                    while "\n" in buf:
                        line, buf = buf.split("\n", 1)
                        line = line.strip()
                        if not line:
                            continue

                        if not ack_received:
                            ack_received = True
                            response = json.loads(line)
                            if "Ok" not in response:
                                print(f"[Niri] Bad handshake: {line}")
                                return
                            continue

                        self._handle_event(line)

        except Exception as e:
            print(f"[Niri] Connection error: {e}")

    def _get_idx(self, id):
        pass

    def _handle_event(self, raw_line: str) -> None:
        try:
            event = json.loads(raw_line)
            if "WorkspacesChanged" in event:
                self._workspaces = {
                    ws["id"]: ws for ws in event["WorkspacesChanged"]["workspaces"]
                }
                _i = 1
                i = 1
                for w in event["WorkspacesChanged"]["workspaces"]:
                    if w["is_active"]:
                        _i = i
                    i += 1
                self._active_workspace = _i
                self.parent.update_workspace(_i, self._workspaces)
                self.parent.change_overview(self._is_overview_open, _i)

            if "WorkspaceActivated" in event:
                id = event["WorkspaceActivated"]["id"]
                ws = self._workspaces.get(id)
                self._active_workspace = ws["idx"]
                self.parent.update_workspace(ws["idx"], self._workspaces)
                self.parent.change_overview(self._is_overview_open, ws["idx"])

            if "OverviewOpenedOrClosed" in event:
                self.parent.change_overview(
                    event["OverviewOpenedOrClosed"]["is_open"], self._active_workspace
                )

                self._is_overview_open = event["OverviewOpenedOrClosed"]["is_open"]

        except Exception as e:
            print(f"[Niri] Parse error: {e} | line: {raw_line}")

    def stop(self):
        self._stop_event.set()


class WorkspaceArea(Gtk.Widget):
    def __init__(self) -> None:
        super().__init__()
        self.no_of_pills = 3
        self.active_pill = 1.0

        self.anim = None

        self.WIDTH = 6
        self.MARGIN = 3
        self.set_size_request(
            self.WIDTH * self.no_of_pills + self.MARGIN * 2, self.WIDTH
        )

        self.set_margin_start(self.MARGIN * 3)

    def do_snapshot(self, snapshot):

        offset = 0
        for i in range(self.no_of_pills):
            i += 1
            ab = abs(self.active_pill - i)
            alpha = 0.3
            current_height = self.WIDTH
            if ab < 1:
                t = 1 - self.WIDTH * ab / self.WIDTH
                current_width = self.WIDTH + 1.5 * t * self.WIDTH * 1.5

                alpha += 0.7 * t
                current_height += self.WIDTH * t / 2
            else:
                current_width = self.WIDTH

            x_pos = offset
            offset += current_width + self.MARGIN

            rect = Graphene.Rect()
            rect.init(
                x_pos,
                13 - current_height / 2,  # 13 is 27/2 ( Window height )
                current_width,
                current_height,
            )

            rounded_rect = Gsk.RoundedRect()
            rounded_rect.init_from_rect(rect, self.WIDTH)

            snapshot.push_rounded_clip(rounded_rect)
            color = Gdk.RGBA()

            color.parse(f"rgba(255, 255, 255, {alpha})")

            snapshot.append_color(color, rect)

            snapshot.pop()

        self.set_size_request(offset + self.MARGIN * 2, self.WIDTH)

    def update(self, idx, ws_list):
        self.no_of_pills = len(ws_list)

        if self.anim:
            self.anim.pause()

        def update_pill_value(value, _):
            self.active_pill = value
            self.queue_draw()

        target = Adw.CallbackAnimationTarget.new(update_pill_value, None)

        self.anim = Adw.TimedAnimation.new(
            self,
            self.active_pill,
            float(idx),
            300,
            target,
        )
        self.anim.play()
