#!/bin/bash

## GENERATED BY GEMINI

# Check if exactly two arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <fan1_speed> <fan2_speed>"
    echo "Example: $0 0 0"
    exit 1
fi

# Assign arguments to variables
FAN1=$1
FAN2=$2

# Define the target path
TARGET_PATH="/sys/module/linuwu_sense/drivers/platform:acer-wmi/acer-wmi/nitro_sense/fan_speed"

# Check if the file exists before writing to it
if [ ! -f "$TARGET_PATH" ]; then
    echo "Error: Target path does not exist."
    echo "Make sure the 'linuwu_sense' module is loaded properly."
    exit 1
fi

# Execute the command
echo "Setting fan speeds to: $FAN1,$FAN2"
echo "$FAN1,$FAN2" | sudo tee "$TARGET_PATH" > /dev/null

# Confirm success
if [ $? -eq 0 ]; then
    echo "Fan speeds updated successfully!"
else
    echo "Failed to update fan speeds."
fi
