background-color=#19120d
text-color=#f0dfd6
border-color=#ffb782
progress-color=source #ffb782

[urgency=low]
border-color=#9f8d83

[urgency=high]
border-color=#ffb4ab
text-color=#ffdad6
background-color=#93000a
